### ISSUE TITLE
Images in CSS not being processed by Webpack

### ISSUE THREAD

**Issue by oyeanuj** [ctrlplusb/react-universally#537]
Hi folks, I'm stuck on this issue where the images specified in the CSS are not being picked up or processed by Webpack.
```css
.img {
  background: url('./logo.png');
}
```
It works if I import an image and then use that as a `src` to an `img` tag. From #15, it seems like this should work but I am unable to achieve that.

Has anyone gotten this working or run into the same problem?
